# Generated by Django 4.1.1 on 2023-03-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividadeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='categoria',
            field=models.ManyToManyField(related_name='Animal', to='atividadeapp.categoria'),
        ),
    ]
